server:
  port: 5555

eureka:
    instance:
        instance-id: gateway-msa-instance
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defalutZone: http://localhost:8761/eureka

spring:
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    application:
        name: apigateway-service
    cloud:
        gateway:
            routes:
                - id: trip-service
                  uri: lb://TRIP-SERVICE
                  predicates:
                    - Path=/trips/**
                  filters: 
                    - CustomAuthGatewayFilter       
                - id: user-service
                  uri: lb://USER-SERVICE
                  predicates:
                    - Path=/user/**
                - id: search-service
                  uri: lb://SEARCH-SERVICE
                  predicates:
                    - Path=/search/**
                
jwt:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400                 

logging:
    level:
        root: INFO