spring:
    config:
        activate:
            on-profile: default
    application:
        name: trip-service
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: mtdb
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    freemarker:
        cache: false  
    redis:
        host: 127.0.0.1
        password:
        port: 6379
    batch:
        job:
            enabled: false
            names: ${job.name:NONE}

logging:
    level:
        root: INFO
        org.springframework.data.mongodb.core.MongoTemplate: INFO

profileValue: default

apiServiceKey: 

---

spring:
    config:
        activate:
            on-profile: test
    application:
        name: trip-service-test
    data:
        mongodb:
            uri: mongodb://localhost:27017/mtdb
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    freemarker:
        cache: false  
    redis:
        host: 127.0.0.1
        password:
        port: 6379    
    batch:
        job:
            enabled: false
            names: ${job.name:NONE}       

server:
    port: 0
    servlet:
        jsp:
            init-parameters.development: true

jwt:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400 

logging:
    level:
        root: INFO
        org.springframework.data.mongodb.core.MongoTemplate: INFO

profileValue: test

apiServiceKey: 